### ISSUE TITLE
Error fetching the Login URL

### ISSUE THREAD

**Issue by PaperjetStudios** [arjusmoon860/strapi-google-auth#12] opened 2022-12-07 07:20 UTC
Hey there,

I'm getting this error when I try get myserver.com/strapi-google-auth/init

"Error fetching the Login URL" 

What could the issue be? Is there something misconfigured?

**Comment by Bespalov-D-A** [comment] 2023-02-12 13:59
I also get 400 error on request MY_STRAPI_SERVER/strapi-google-auth/init

response:
`{
    "data": null,
    "error": {
        "status": 400,
        "name": "BadRequestError",
        "message": "Error fetching the Login URL",
        "details": null
    }
}`

**Comment by Bespalov-D-A** [comment] 2023-02-12 17:00
I got into the intestines and found the cause of the error:

YOU_PROJECT_STRAPI/node_modules/strapi-google-auth/server/services/google.js
problem 69 line
`let scopesObject = JSON.parse(scopesData);` 
change to:
```
            let scopesObject = null                                                                    
            try {
                scopesObject = JSON.parse(scopesData);
            } catch(e) {
                console.log(e)
            }
            scopesObject = !scopesObject ? scopesData : scopesObject;

```

**Comment by arjusmoon860** [comment] 2023-10-03 13:02
The plugin now works with the latest version of strapi & node 18.x.x. Please read the documentation given in the git repo.
Closing this issue for now. Please reopen if you are facing any issue.

Thanks.

**Closed as completed by arjusmoon860** 2023-10-03 13:02 UTC

**Comment by AnalyteSoftware** [comment] 2024-01-18 12:57
Hi, 

I am still getting the same error but for the /user-profile fetch.

{"data":null,"error":{"status":400,"name":"BadRequestError","message":"Error occured while fetching the user profile","details":null}}
